
import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import { supabase } from '@/lib/supabase';
import { useRouter } from 'next/router';
import { useEffect, useState, useRef } from 'react';
import _ from 'lodash';
import HUD from '@/components/HUD';
import Map from '@/components/Map';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function GamePage({session}) {
  var [game, setGame] = useState(null);
  var [isEditing, setIsEditing] = useState(false);
  var [objectTypes, _setObjectTypes] = useState({});
  var [drawingMode, setDrawingMode] = useState(false);
  var [selectedMaterialId, setSelectedMaterialId] = useState(null);

  // Create refs for state to avoid race conditions
  const stateRef = useRef({
    game: null,
    objectTypes: {}
  });

  const router = useRouter();
  const { gameId } = router.query;
  console.log(gameId)
  useEffect(() => {
    if (gameId) {
      async function fetchGameData() {
        // Fetch game
        const { data: gameData, error: gameError } = await supabase
          .from('games')
          .select('*')
          .eq('id', gameId)
          .eq('user_id', session.user.id)
          .single();

        if (gameError) {
          console.log(gameError);
          return;
        }

        setGame(gameData);
        stateRef.current.game = gameData;

        // Fetch object types for this game
        const { data: objectTypesData, error: objectTypesError } = await supabase
          .from('object_types')
          .select('*')
          .eq('game_id', gameId);

        if (objectTypesError) {
          console.log(objectTypesError);
          return;
        }

        // Convert array to object with id as key
        const objectTypesObj = {};
        objectTypesData.forEach(ot => {
          objectTypesObj[ot.id] = ot.data;
        });
        setObjectTypes(objectTypesObj);
        stateRef.current.objectTypes = objectTypesObj;
      }

      fetchGameData();
    }
  }, [gameId]);

  console.log('game', game);

  var updateGame = async (updatedGame, {updateSupabase = true, updateState = true} = {}) => {
    if (updateSupabase) {
      const { data, error } = await supabase
        .from('games')
        .update(updatedGame)
        .eq('id', gameId)
        .eq('user_id', session.user.id);
    }

    if (updateState) {
      setGame(updatedGame);
      stateRef.current.game = updatedGame;
    }
  }

  // Debounced version for drawing materials
  const debouncedUpdateGame = _.debounce(async (updatedGame) => {
    const { data, error } = await supabase
      .from('games')
      .update(updatedGame)
      .eq('id', gameId)
      .eq('user_id', session.user.id);
  }, 500);

  // Function for drawing that updates state immediately but debounces database updates
  const updateGameForDrawing = (updatedGame) => {
    // Update state immediately for responsive UI
    setGame(updatedGame);
    stateRef.current.game = updatedGame;

    // Debounce the database update
    debouncedUpdateGame(updatedGame);
  }

  const setObjectTypes = (newObjectTypes) => {
    _setObjectTypes(newObjectTypes);
    stateRef.current.objectTypes = newObjectTypes;
  }

  return game && (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <HUD
          isEditing={isEditing}
          setIsEditing={setIsEditing}
          game={game}
          updateGame={updateGame}
          objectTypes={objectTypes}
          setObjectTypes={setObjectTypes}
          session={session}
          drawingMode={drawingMode}
          setDrawingMode={setDrawingMode}
          selectedMaterialId={selectedMaterialId}
          setSelectedMaterialId={setSelectedMaterialId}
        />
        <Map
          game={game}
          objectTypes={objectTypes}
          isEditing={isEditing}
          updateGame={updateGame}
          debouncedUpdateGame={updateGameForDrawing}
          drawingMode={drawingMode}
          selectedMaterialId={selectedMaterialId}
          stateRef={stateRef}
        />
      </div>
    </>
  );
}
